### ISSUE TITLE
Support whitespace between element selector and class selector

### ISSUE THREAD

**Issue by tim-sueberkrueb** [Ableton/aqt-stylesheets#45]
It's currently not possible to use a whitespace between an element selector and a class selector.
So for example this will work:
```css
QQuickRectangle.rect1 { /*...*/ }
```
But this won't:
```css
QQuickRectangle .rect2 { /*...*/ }
```
My personal use case for this is the usage of a css precompiler (less) which generates a whitespace at this position.
BTW, this is a really nice project!

**Comment by gck-ableton** [comment]
Hi, thanks for your feedback.  I'm not sure I understand your problem.  `A.b` in CSS is not the same as `A .b`.  The first is a selector for every `A` with class `b`, the second a selector for every descendant with a class `.b` below an `A`.  As far what I can see aqt-stylesheets supports both.

**Comment by tim-sueberkrueb** [comment]
@gck-ableton Oh, I'm sorry, I'm mistaken here. I did understand this CSS feature wrong. 
Thanks for clarifying (man lernt immer dazu ;)).
Keep up this great project!
